%**************************************************************************
% Jeffrey Csank, 12/1/2014
% This file contains the gui and allows the acceleration schedule and
% acceleration controller to be retuned.  Can be called as part of the
% complete design process or individually after the controller has been
% designed.
%**************************************************************************

%-------------------
% Configure the GUI window
%-------------------
S.fh = figure('units','normalized','position',[0.5 0.1 0.25 0.35],...
    'menubar','none',...
    'name','TTECTrA: Acceleration Limiter',...
    'numbertitle','off',...
    'visible','off',...
    'resize','on');

%-------------------
% Acceleration Schedule
%-------------------
S.as = uipanel('units','normalized',...
    'pos',[0.05 0.55 0.90 0.425],...
    'fontsize',13,...
    'TitlePosition', 'centertop',...
    'Title', 'Acceleration Schedule');

%---- High Pressure Compressor ----
S.ahpc_txt = uicontrol(S.as,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.70 0.55 0.225],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','HPC Surge Margin');

S.ahpc_in = uicontrol(S.as,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.70 0.30 0.225], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%---- Turbine Inlet Temperature (T40) ----
S.at40_txt = uicontrol(S.as,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.4 0.55 0.225],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','T40');

S.at40_in = uicontrol(S.as,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.4 0.30 0.225], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%-------------------
% Design the acceleration controller
%-------------------

%---- Controller gain ----
S.akp_txt = uicontrol(S.fh,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.4 0.55 0.1],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','Controller Gain');

S.akp_in = uicontrol(S.fh,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.4 0.30 0.1], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%---- Ki -----
S.atc_txt = uicontrol(S.fh,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.275 0.55 0.1],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','Time Constant');

S.atc_in = uicontrol(S.fh,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.275 0.30 0.1], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%----------------------
% Execution Commands
%----------------------
S.aschedule_execute = uicontrol(S.as,...
    'style','push',...
    'unit','normalized',...
    'position',[0.2 0.075 0.6 0.25],...
    'fontsize',12,...
    'string','ReCompute Accel Schedule',...
    'enable', 'on',...
    'callback','create_accel_schedule');

S.a_execute = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.05 0.075 0.4 0.15],...
    'fontsize',12,...
    'string','Execute',...
    'enable', 'on',...
    'callback','tune_accel_controller');

S.final = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.55 0.075 0.4 0.15],...
    'fontsize',12,...
    'string','Finish',...
    'enable', 'on',...
    'callback','uiresume');

%----------------------
% Load the current controller parameters
%----------------------
if isfield(ttectra_in,'SMLimit')
    if isfield(ttectra_in.SMLimit,'Accel')
        set(S.ahpc_in,'String',num2str(ttectra_in.SMLimit.Accel));
    end
    if isfield(ttectra_in.SMLimit,'T40')
        set(S.at40_in,'String',num2str(ttectra_in.SMLimit.T40));
    end
end

if isfield(ttectra_in,'controller')
    if isfield(ttectra_in.controller,'accel_k')
        set(S.akp_in,'String',num2str(ttectra_in.controller.accel_k));
    end
    if isfield(ttectra_in.controller,'accel_bw')
        set(S.atc_in,'String',num2str(ttectra_in.controller.accel_bw));
    end
end

%----------------------
% Redesign
%----------------------
%create_accel_schedule
ManualTune_accelschedule


% move and show the gui
movegui(S.fh,'northeast')
set(S.fh,'visible','on'); % Make the GUI visible.

uiwait;    

set(S.fh,'visible','off'); % Make the GUI visible.