%**************************************************************************
% Jeffrey Csank, 12/1/2014
% This file contains the gui command and allows the integral windup
% protection gain to be returned.  This gui can be called as part of the
% complete controller design or individually by type gui_iwp at the MATLAB 
% command prompt.
%**************************************************************************

%--------------------------------
% Configure the GUI window
%--------------------------------
S.fh = figure('units','normalized','position',[0.5 0.1 0.25 0.125],...
    'menubar','none',...
    'name','TTECTrA: Integral Windup Protection',...
    'numbertitle','off',...
    'visible','off',...
    'resize','on');
% iwp gain
S.iwp_txt = uicontrol(S.fh,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.6 0.55 0.30],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','Integral Windup Gain');

S.iwp_in = uicontrol(S.fh,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.6 0.30 0.30], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

% Command
S.a_execute = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.05 0.075 0.4 0.40],...
    'fontsize',12,...
    'string','Execute',...
    'enable', 'on',...
    'callback','tune_iwp');

S.final = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.55 0.075 0.4 0.40],...
    'fontsize',12,...
    'string','Finish',...
    'enable', 'on',...
    'callback','uiresume');

%update command
if isfield(ttectra_in,'controller')
    if isfield(ttectra_in.controller,'IWP_gain')
        set(S.iwp_in,'String',num2str(ttectra_in.controller.IWP_gain));
    end
end

%perform close loop sim with new gain
ManualTune_iwp

%--- move and show the gui
movegui(S.fh,'northeast')
set(S.fh,'visible','on'); % Make the GUI visible.

uiwait;    

set(S.fh,'visible','off'); % Make the GUI visible.