%**************************************************************************
% Jeffrey Csank, 12/1/2014
% This file contains the gui and allows the deceletaion limiter to be 
% retuned.  Can be called as part of the complete design process or 
% individually after the controller has been designed by typing gui_decel
% at the MATLAB command prompt.
%**************************************************************************

%--------------------------------
% Configure the GUI window
%--------------------------------
S.fh = figure('units','normalized','position',[0.5 0.1 0.25 0.2],...
    'menubar','none',...
    'name','TTECTrA: Deceleration Limiter',...
    'numbertitle','off',...
    'visible','off',...
    'resize','on');

%---- LPC Surge Margin ----
S.dlpc_txt = uicontrol(S.fh,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.70 0.55 0.2],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','LPC Surge Margin');

S.dlpc_in = uicontrol(S.fh,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.70 0.30 0.2], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%---- Fuel to Air Ratio ----
S.dfar_txt = uicontrol(S.fh,...
    'Style','text',...
    'unit','normalized',...
    'position',[0.05 0.40 0.55 0.2],...
    'fontsize',13,...
    'HorizontalAlignment','center',...
    'string','Fuel to Air Ratio');

S.dfar_in = uicontrol(S.fh,...
    'style','edit',...
    'unit','normalized',...
    'position',[0.65 0.40 0.30 0.2], ...
    'HorizontalAlignment','left',...
    'fontsize',11,...
    'backgroundcolor','white');

%---- Commands ----
S.a_execute = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.05 0.075 0.4 0.25],...
    'fontsize',12,...
    'string','Execute',...
    'enable', 'on',...
    'callback','tune_decel');

S.final = uicontrol(S.fh,...
    'style','push',...
    'unit','normalized',...
    'position',[0.55 0.075 0.4 0.25],...
    'fontsize',12,...
    'string','Finish',...
    'enable', 'on',...
    'callback','uiresume');

%---- Update inputs ----
if isfield(ttectra_in,'SMLimit')
    if isfield(ttectra_in.SMLimit,'Decel')
        set(S.dlpc_in,'String',num2str(ttectra_in.SMLimit.Decel));
    end
    if isfield(ttectra_in.SMLimit,'FARmin')
        set(S.dfar_in,'String',num2str(ttectra_in.SMLimit.FARmin));
    end
end

% Determine decel limit
ManualTune_decellimit

%--- move and show the gui
movegui(S.fh,'northeast')
set(S.fh,'visible','on'); % Make the GUI visible.

uiwait;    

set(S.fh,'visible','off'); % Make the GUI visible.